version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.2
    commands:
      - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
      - php composer-setup.php --install-dir=/usr/local/bin --filename=composer
  pre_build:
    commands:
      - composer install
      - npm install
      - composer require --dev phpunit/phpunit
  build:
    commands:
      - ./vendor/bin/phpunit --testsuite=Unit

artifacts:
  files:
    - "**/*"
  name: $(date +%Y-%m-%dT%H:%M:%S).zip

proxy:
  upload-artifacts: yes
  logs: yes